require:
  - 'rubocop-performance'
  - 'rubocop-rails'

AllCops:
  Exclude:
  - 'db/**/*'
  - 'config/**/*'
  - 'script/**/*'
  - 'bin/*'

Metrics/LineLength:
  Max: 99
  AutoCorrect: true
  IgnoredPatterns: ['\A*#']

Metrics/BlockLength:
  Max: 50
  Exclude:
  - 'spec/**/*'

Style/Documentation:
  Enabled: false